using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Sky.Orbital.Elements;
using Sky.Orbital.Frames;

namespace Sky.Orbital.Tests.CrossCheck;

/// <summary>
/// Reference data generated by tools/reference/generate_skyfield_reference.py with Skyfield,
/// which shares no code with Sky. See the file's "notes" and "versions" fields for details.
/// </summary>
internal sealed class SkyfieldReference
{
    private static readonly Lazy<SkyfieldReference> LazyInstance = new(Load);

    public static SkyfieldReference Instance => LazyInstance.Value;

    [JsonPropertyName("elements")]
    public required OmmRecord Elements { get; init; }

    [JsonPropertyName("observer")]
    public required ObserverRecord Observer { get; init; }

    [JsonPropertyName("states")]
    public required IReadOnlyList<StateRecord> States { get; init; }

    [JsonPropertyName("passes")]
    public required IReadOnlyList<PassRecord> Passes { get; init; }

    public MeanElements MeanElements => new()
    {
        CatalogNumber = Elements.NoradCatId,
        Epoch = DateTimeOffset.Parse(Elements.Epoch + "Z", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal),
        MeanMotion = Elements.MeanMotion,
        Eccentricity = Elements.Eccentricity,
        Inclination = Elements.Inclination,
        RightAscensionOfAscendingNode = Elements.RaOfAscNode,
        ArgumentOfPericenter = Elements.ArgOfPericenter,
        MeanAnomaly = Elements.MeanAnomaly,
        BStar = Elements.BStar,
        MeanMotionDot = Elements.MeanMotionDot,
        MeanMotionDdot = Elements.MeanMotionDdot,
    };

    public Geodetic ObserverLocation => new(Observer.LatitudeDeg, Observer.LongitudeDeg, Observer.HeightM / 1000.0);

    private static SkyfieldReference Load()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "Data", "Skyfield", "iss-phoenix-2026-09-24.json");
        return JsonSerializer.Deserialize<SkyfieldReference>(File.ReadAllText(path))
            ?? throw new InvalidDataException($"Could not read {path}.");
    }

    internal sealed record OmmRecord(
        [property: JsonPropertyName("NORAD_CAT_ID")] long NoradCatId,
        [property: JsonPropertyName("EPOCH")] string Epoch,
        [property: JsonPropertyName("MEAN_MOTION")] double MeanMotion,
        [property: JsonPropertyName("ECCENTRICITY")] double Eccentricity,
        [property: JsonPropertyName("INCLINATION")] double Inclination,
        [property: JsonPropertyName("RA_OF_ASC_NODE")] double RaOfAscNode,
        [property: JsonPropertyName("ARG_OF_PERICENTER")] double ArgOfPericenter,
        [property: JsonPropertyName("MEAN_ANOMALY")] double MeanAnomaly,
        [property: JsonPropertyName("BSTAR")] double BStar,
        [property: JsonPropertyName("MEAN_MOTION_DOT")] double MeanMotionDot,
        [property: JsonPropertyName("MEAN_MOTION_DDOT")] double MeanMotionDdot);

    internal sealed record ObserverRecord(
        [property: JsonPropertyName("latitude_deg")] double LatitudeDeg,
        [property: JsonPropertyName("longitude_deg")] double LongitudeDeg,
        [property: JsonPropertyName("height_m")] double HeightM);

    internal sealed record StateRecord(
        [property: JsonPropertyName("utc")] DateTimeOffset Utc,
        [property: JsonPropertyName("ut1_minus_utc_s")] double Ut1MinusUtcSeconds,
        [property: JsonPropertyName("teme_km")] double[] TemeKm,
        [property: JsonPropertyName("teme_km_s")] double[] TemeKmPerSecond,
        [property: JsonPropertyName("earth_fixed_km")] double[] EarthFixedKm,
        [property: JsonPropertyName("earth_fixed_km_s")] double[] EarthFixedKmPerSecond,
        [property: JsonPropertyName("subpoint")] SubpointRecord Subpoint,
        [property: JsonPropertyName("look")] LookRecord Look);

    internal sealed record SubpointRecord(
        [property: JsonPropertyName("latitude_deg")] double LatitudeDeg,
        [property: JsonPropertyName("longitude_deg")] double LongitudeDeg,
        [property: JsonPropertyName("height_km")] double HeightKm,
        [property: JsonPropertyName("latitude_converged_deg")] double LatitudeConvergedDeg,
        [property: JsonPropertyName("height_converged_km")] double HeightConvergedKm);

    internal sealed record LookRecord(
        [property: JsonPropertyName("azimuth_deg")] double AzimuthDeg,
        [property: JsonPropertyName("elevation_deg")] double ElevationDeg,
        [property: JsonPropertyName("range_km")] double RangeKm,
        [property: JsonPropertyName("range_rate_km_s")] double RangeRateKmPerSecond);

    internal sealed record PassRecord(
        [property: JsonPropertyName("rise")] EventRecord Rise,
        [property: JsonPropertyName("culmination")] EventRecord Culmination,
        [property: JsonPropertyName("set")] EventRecord Set);

    internal sealed record EventRecord(
        [property: JsonPropertyName("utc")] DateTimeOffset Utc,
        [property: JsonPropertyName("azimuth_deg")] double AzimuthDeg,
        [property: JsonPropertyName("elevation_deg")] double ElevationDeg);
}
