using System.Text.Json;
using System.Text.Json.Serialization;

namespace Sky.Orbital.Tests.CrossCheck;

/// <summary>
/// Reference data generated by tools/reference/generate_skyfield_visibility_reference.py: the Sun
/// from JPL's DE421 through Skyfield, the Earth's shadow by an independent line-ellipsoid quadratic,
/// civil twilight, and each reference pass's visible parts. See the file's "notes".
/// </summary>
internal sealed class VisibilityReference
{
    private static readonly Lazy<VisibilityReference> LazyInstance = new(Load);

    public static VisibilityReference Instance => LazyInstance.Value;

    [JsonPropertyName("sun_week")]
    public required IReadOnlyList<SunRecord> SunWeek { get; init; }

    [JsonPropertyName("sun_century")]
    public required IReadOnlyList<SunPlaceRecord> SunCentury { get; init; }

    [JsonPropertyName("shadow")]
    public required IReadOnlyList<TransitionRecord> Shadow { get; init; }

    [JsonPropertyName("skyfield_sphere_shadow")]
    public required IReadOnlyList<TransitionRecord> SkyfieldSphereShadow { get; init; }

    [JsonPropertyName("twilight")]
    public required IReadOnlyList<TransitionRecord> Twilight { get; init; }

    [JsonPropertyName("passes")]
    public required IReadOnlyList<PassWindowsRecord> Passes { get; init; }

    private static VisibilityReference Load()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "Data", "Skyfield", "iss-phoenix-visibility-2026-09-24.json");
        return JsonSerializer.Deserialize<VisibilityReference>(File.ReadAllText(path))
            ?? throw new InvalidDataException($"Could not read {path}.");
    }

    internal sealed record SunRecord(
        [property: JsonPropertyName("utc")] DateTimeOffset Utc,
        [property: JsonPropertyName("earth_fixed_km")] double[] EarthFixedKm,
        [property: JsonPropertyName("altitude_deg")] double? AltitudeDeg)
    {
        public Vec3 EarthFixed => new(EarthFixedKm[0], EarthFixedKm[1], EarthFixedKm[2]);
    }

    internal sealed record SunPlaceRecord(
        [property: JsonPropertyName("tt_jd_whole")] double TtJdWhole,
        [property: JsonPropertyName("tt_jd_fraction")] double TtJdFraction,
        [property: JsonPropertyName("right_ascension_deg")] double RightAscensionDeg,
        [property: JsonPropertyName("declination_deg")] double DeclinationDeg,
        [property: JsonPropertyName("distance_au")] double DistanceAu,
        [property: JsonPropertyName("equation_of_equinoxes_rad")] double EquationOfEquinoxesRad);

    internal sealed record TransitionRecord(
        [property: JsonPropertyName("utc")] DateTimeOffset Utc,
        [property: JsonPropertyName("kind")] string Kind,
        [property: JsonPropertyName("sun_earth_fixed_km")] double[]? SunEarthFixedKm)
    {
        public Vec3 SunEarthFixed => new(SunEarthFixedKm![0], SunEarthFixedKm[1], SunEarthFixedKm[2]);
    }

    internal sealed record PassWindowsRecord(
        [property: JsonPropertyName("rise_utc")] DateTimeOffset RiseUtc,
        [property: JsonPropertyName("set_utc")] DateTimeOffset SetUtc,
        [property: JsonPropertyName("windows")] IReadOnlyList<WindowRecord> Windows);

    internal sealed record WindowRecord(
        [property: JsonPropertyName("start_utc")] DateTimeOffset StartUtc,
        [property: JsonPropertyName("starts_because")] string StartsBecause,
        [property: JsonPropertyName("end_utc")] DateTimeOffset EndUtc,
        [property: JsonPropertyName("ends_because")] string EndsBecause,
        [property: JsonPropertyName("highest")] SkyfieldReference.EventRecord Highest);
}
